name:                marlowe-explorer
version:             0.1.0.0
github:              "input-ouptut-hk/marlowe-explorer"
license:             Apache-2.0
author:              "Input Output"
copyright:           "2023 Input Output"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/input-output-hk/marlowe-explorer>

dependencies:
- base >= 4.7 && < 5
- aeson
- base16-bytestring
- blaze-html
- blaze-markup
- bytestring
- containers
- errors
- extra
- http-client
- http-conduit
- http-types
- scientific
- servant-blaze
- servant-server
- text
- wai
- warp
- wl-pprint

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - mtl
  - newtype-generics
  - optparse-applicative
  - time

executables:
  marlowe-explorer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - marlowe-explorer
    - newtype-generics

tests:
  marlowe-explorer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - marlowe-explorer
    - hspec
    - hspec-wai
    - aeson

