name: "Nix build"
on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

permissions:
  contents: read
  
jobs:
  test-nix-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - uses: cachix/install-nix-action@daddc62a2e67d1decb56e028c9fa68344b9b7c2a
      with:
        nix_path: nixpkgs=channel:nixos-23.05
    - run: nix-build shell.nix
    - run: nix-shell --run "hlint src && fix-hie && git diff --exit-code hie.yaml"
